### PR TITLE
Allow locking people to anchor tracks

### PR DESCRIPTION
**Pull request by jaresty**
Why?

It is more intuitive to lock the person who is going to hold context
than to remove the person who is not holding context.

### CODE REVIEW

**Comment by sweinstein22** [comment]
Just on a first pass, it looks like this PR breaks other lock functionality.
- Locking a person while they are not on a lane no longer has an effect
  This is problematic both from a UX perspective and in that there's no way to keep a person out of the pairing rotation for the day.
- Sweeping a lane that has a locked person in it does not unlock the person
  It would be a better UX to unlock the person on sweep as the most common use case for sweeping a lane is not that the people should not be paired for the day, but rather that the track of work they were doing the previous day has been completed.

This also seems to break some of the recommender logic:
- On a team of three, having two locked people on one lane and one unlocked person who hasn't been put on a lane yet. The randomize button doesn't pull in the person who's out and put them in a new lane.

I haven't tested these changes further, or run anything against them with more than three people, so I would recommend more thorough testing as well as fixes for the bugs mentioned above.

**Comment by jaresty** [comment]
Thanks for the feedback!  I believe that the bugs mentioned above in your feedback are now fixed. 
- I've added a new test for the recommender bug you found as well as manually investigating/fixing the bug related to users being marked as "out."  
- I've also adjusted the "sweep" behavior to unlock users that are swept as recommended.

**Comment by sweinstein22** [comment]
Thanks for addressing the feedback I gave previously! I'm still seeing some weird behavior, still only testing with three people:
- Roles are not all assigned to a lane on the first shuffle click. This runs counter to the roles behavior, which should be that they all get assigned on every shuffle
- If you lock a person and lock the lane, it looks like the lane lock doesn't actually take effect; I'd expect both people to remain locked in place, but the unlocked person gets shuffled around
  - To that point, if both the lane lock and the person lock are still at play, I'd expect there to be a difference when using the two. Namely, I'd expect that role still shuffle around if only the person lock is used, whereas I'd expect them to stick if the lane lock is used. It seems redundant to have both if the person lock overrides the lane lock, and if there's no difference between the two

Again this isn't thorough testing, and it still seems like more changes and more testing are necessary.

**Comment by jaresty** [comment]
I'll keep looking into this behavior -- I just checked and I think that role bug you mentioned is on the `v2` branch too.  It does make sense to consider role assignment regardless of people's locked-ness.  That's a tricky one. Thinking...

**Comment by jaresty** [comment]
There is a separate PR #28 now for fixing the role assignment bug.  I added tests for the locked-lane case and fixed a bug related to that, as well as adding a test for ensuring that the original argument to calculateMovesToBestPairing does not get modified, which should ensure that unlocked lanes are treated as unlocked for the purpose of calculating role assignments.

**Comment by jaresty** [comment]
Closing since there hasn't been any movement on this in a long time.

**Pull request closed without merging**
